### ISSUE TITLE
ne fonctionne plus avec la nouvelle version du site

### ISSUE THREAD

**Issue by wbui567** [VinceGsm/Suctionator#10]
le code des pages à changé. du coup, ça récup plus automatiquement.
j'espère qu'un update sera possible.
l'url est mtn: www2.palixi.com

merci

**Comment by VinceGusmini** [comment]
Salutations,
Suite à l'instabilité de l'hébergement récent et son changement régulier de code ce projet est mit en pause afin de retrouver une stabilité de l'environnement cible.

_**Reprise estimé cet automne**_

**Comment by VinceGusmini** [comment]
Le site Tirexo/Palixi ayant définitivement fermé ce projet s'adaptera ultérieurement à un site différent afin de maintenir l'objectif principal d'aspiration de lien.

_**Reprise estimé 2022**_

**Comment by VinceGsm** [comment]
Site de retour, pas de garantie que le projet soit toujours maintenable mais en attendant que je me penche là dessus je réouvre l'issue

**Comment by wbui567** [comment]
Bonjour @VinceGsm , 
je souhaite savoir s'il serait possible de faire fonctionner l'app avec le site actuel et si il es serait possible d'inclure la récupération de tous les liens de tous les hébergeurs quelque soit la qualité.

Merci d'avance 
Cdlt
